export const SHOW_NEW_CLASS = 'SHOW_NEW_CLASS';
export const SHOW_ADD_STUDENT = 'SHOW_ADD_STUDENT';
export const SHOW_STUDENTS = 'SHOW_STUDENTS';
export const ADD_CLASS = 'ADD_CLASS';
export const GET_STUDENTS_SUCCESS = 'GET_STUDENTS_SUCCESS';
export const ADD_STUDENTS_TO_CLASS = 'ADD_STUDENTS_TO_CLASS';
export const DELETE_CLASS = 'DELETE_CLASS';
